// reg832.h based on reg832.pdf
// by WDA 18 feb 2007
sfr at	0x80	P0;	//PORT 0	
sfr at	0x81	SP;	//STACK POINTER
sfr at	0x82	DPL;	//DATA POINTER - LOW BYTE
sfr at	0x83	DPH;	//DATA POINTER - HIGH BYTE
sfr at	0x84	DPP;	//DATA POINTER - PAGE BYTE
sfr at	0x87	PCON;	//POWER CONTROL
sfr at	0x88	TCON;	//TIMER CONTROL
sfr at	0x89	TMOD;	//TIMER MODE
sfr at	0x8A	TL0;	//TIMER 0 - LOW BYTE
sfr at	0x8B	TL1;	//TIMER 1 - LOW BYTE
sfr at	0x8C	TH0;	//TIMER 0 - HIGH BYTE
sfr at	0x8D	TH1;	//TIMER 1 - HIGH BYTE
sfr at	0x90	P1;	//PORT 1
sfr at	0x98	SCON;	//SERIAL PORT CONTROL
sfr at	0x99	SBUF;	//SERIAL PORT BUFFER
sfr at	0x9A	I2CDAT;	//I2C DATA REGISTER
sfr at	0x9B	I2CADD;	//I2C ADDRESS REGISTER
sfr at	0x9E	T3CON;	//TIMER 3 CONTROL
sfr at	0x9D	T3FD;	//TIMER 3 FRACTIONAL DIVIDER
sfr at	0xA0	P2;	//PORT 2
sfr at	0xA1	TIMECON;	//TIC CONTROL
sfr at	0xA2	HTHSEC;	//TIC - HTHSEC DATA
sfr at	0xA3	SEC;	//TIC - SEC DATA
sfr at	0xA4	MIN;	//TIC - MIN DATA
sfr at	0xA5	HOUR;	//TIC - HOUR DATA
sfr at	0xA6	INTVAL;	//TIC INTERVAL REGISTER
sfr at	0xA7	DPCON;	//DUAL DATA POINTER CONTROL REGISTER
sfr at	0xA8	IE;	//INTERRUPT ENABLE 1
sfr at	0xA9	IEIP2;	//INTERRUPT ENABLE 2
sfr at	0xAE	PWMCON;	//PWM CONTROL REGISTER
sfr at	0xAF	CFG832;	//GENERAL FLASH/PWM CONTROL REGISTER
sfr at	0xB0	P3;	//PORT 3
sfr at	0xB1	PWM0L;	//PWM DATA REGISTER
sfr at	0xB2	PWM0H;	//PWM DATA REGISTER
sfr at	0xB3	PWM1L;	//PWM DATA REGISTER
sfr at	0xB4	PWM1H;	//PWM DATA REGISTER
sfr at	0xB7	SPH;	//EXTENDED STACK POINTER REGISTER
sfr at	0xB8	IP;	//INTERRUPT PRIORITY
sfr at	0xB9	ECON;	//FLASH EEPROM CONTROL
sfr at	0xBC	EDATA1;	//FLASH EEPROM DATA1
sfr at	0xBD	EDATA2;	//FLASH EEPROM DATA2
sfr at	0xBE	EDATA3;	//FLASH EEPROM DATA3
sfr at	0xBF	EDATA4;	//FLASH EEPROM DATA4
sfr at	0xC0	WDCON;	//WATCHDOG TIMER CONTROL
sfr at	0xC2	CHIPID;	//CHIPID REGISTER
sfr at	0xC6	EADRL;	//FLASH EEPROM PAGE ADDRESS - LOW BYTE
sfr at	0xC7	EADRH;	//FLASH EEPROM PAGE ADDRESS - LOW BYTE
sfr at	0xC8	T2CON;	//TIMER 2 CONTROL
sfr at	0xCA	RCAP2L;	//TIMER 2 CAPTURE REGISTER - LOW BYTE
sfr at	0xCB	RCAP2H;	//TIMER 2 CAPTURE REGISTER - HIGH BYTE
sfr at	0xCC	TL2;	//TIMER 2 - LOW BYTE
sfr at	0xCD	TH2;	//TIMER 2 - HIGH BYTE
sfr at	0xD0	PSW;	//PROGRAM STATUS WORD
sfr at	0xD2	DMAL;	//DMA ADDRESS LOW BYTE
sfr at	0xD3	DMAH;	//DMA ADDRESS HIGH BYTE
sfr at	0xD4	DMAP;	//DMA ADDRESS PAGE BYTE
sfr at	0xD7	PLLCON;	//PLL CONTROL REGISTER
sfr at	0xD8	ADCCON2;	//ADC CONTROL
sfr at	0xD9	ADCDATAL;	//ADC DATA LOW BYTE
sfr at	0xDA	ADCDATAH;	//ADC DATA HIGH BYTE
sfr at	0xDF	PSMCON;	//POWER SUPPLY MONITOR
sfr at	0xE0	ACC;	//ACCUMULATOR
sfr at	0xE8	DCON;	//D1 AND D0 CONTROL
sfr at	0xE8	I2CCON;	//I2C CONTROL
sfr at	0xEF	ADCCON1;	//ADC CONTROL
sfr at	0xF0	B;	//MULTIPLICATION REGISTER
sfr at	0xF1	ADCOFSL;	//ADC OFFSET LOW BYTE
sfr at	0xF2	ADCOFSH;	//ADC OFFSET HIGH BYTE
sfr at	0xF3	ADCGAINL;	//ADC GAIN LOW BYTE
sfr at	0xF4	ADCGAINH;	//ADC GAIN HIGH BYTE
sfr at	0xF5	ADCCON3;	//ADC CONTROL
sfr at	0xF7	SPIDAT;	//SPI DATA REGISTER
sfr at	0xF8	SPICON;	//SPI CONTROL REGISTER
sfr at	0xF9	DAC0L;	//DAC0 LOW BYTE
sfr at	0xFA	DAC0H;	//DAC0 HIGH BYTE
sfr at	0xFB	DAC1L;	//DAC1 LOW BYTE
sfr at	0xFC	DAC1H;	//DAC1 HIGH BYTE
sfr at	0xFD	DACCON;	//DAC CONTROL REGISTER
sbit at	0x88	IT0;	//TCON.0 - EXT. INTERRUPT 0 TYPE
sbit at	0x89	IE0;	//TCON.1 - EXT. INTERRUPT 0 EDGE FLAG
sbit at	0x8A	IT1;	//TCON.2 - EXT. INTERRUPT 1 TYPE
sbit at	0x8B	IE1;	//TCON.3 - EXT. INTERRUPT 1 EDGE FLAG
sbit at	0x8C	TR0;	//TCON.4 - TIMER 0 ON/OFF CONTROL
sbit at	0x8D	TF0;	//TCON.5 - TIMER 0 OVERFLOW FLAG
sbit at	0x8E	TR1;	//TCON.6 - TIMER 1 ON/OFF CONTROL
sbit at	0x8F	TF1;	//TCON.7 - TIMER 1 OVERFLOW FLAG
sbit at	0x90	T2;	//P1.0 - TIMER 2 TRIGGER INPUT
sbit at	0x91	T2EX;	//P1.1 - TIMER 2 COUNT INPUT
sbit at	0x98	RI;	//SCON.0 - RECEIVE INTERRUPT FLAG
sbit at	0x99	TI;	//SCON.1 - TRANSMIT INTERRUPT FLAG
sbit at	0x9A	RB8;	//SCON.2 - RECEIVE BIT 8
sbit at	0x9B	TB8;	//SCON.3 - TRANSMIT BIT 8
sbit at	0x9C	REN;	//SCON.4 - RECEIVE ENABLE
sbit at	0x9D	SM2;	//SCON.5 - SERIAL MODE CONTROL BIT 2
sbit at	0x9E	SM1;	//SCON.6 - SERIAL MODE CONTROL BIT 1
sbit at	0x9F	SM0;	//SCON.7 - SERIAL MODE CONTROL BIT 0
sbit at	0xA8	EX0;	//IE.0 - EXTERNAL INTERRUPT 0 ENABLE
sbit at	0xA9	ET0;	//IE.1 - TIMER 0 INTERRUPT ENABLE
sbit at	0xAA	EX1;	//IE.2 - EXTERNAL INTERRUPT 1 ENABLE
sbit at	0xAB	ET1;	//IE.3 - TIMER 1 INTERRUPT ENABLE
sbit at	0xAC	ES;	//IE.4 - SERIAL PORT INTERRUPT ENABLE
sbit at	0xAD	ET2;	//IE.5 - TIMER 2 INTERRUPT ENABLE
sbit at	0xAE	EADC;	//IE.6 - ENABLE ADC INTURRUPT
sbit at	0xAF	EA;	//IE.7 - GLOBAL INTERRUPT ENABLE
sbit at	0xB0	RXD;	//P3.0 - SERIAL PORT RECEIVE INPUT
sbit at	0xB1	TXD;	//P3.1 - SERIAL PORT TRANSMIT OUTPUT
sbit at	0xB2	INT0;	//P3.2 - EXTERNAL INTERRUPT 0 INPUT
sbit at	0xB3	INT1;	//P3.3 - EXTERNAL INTERRUPT 1 INPUT
sbit at	0xB4	T0;	//P3.4 - TIMER 0 COUNT INPUT
sbit at	0xB5	T1;	//P3.5 - TIMER 1 COUNT INPUT
sbit at	0xB6	WR;	//P3.6 - WRITE CONTROL FOR EXT. MEMORY
sbit at	0xB7	RD;	//P3.7 - READ CONTROL FOR EXT. MEMORY
sbit at	0xB8	PX0;	//IP.0 - EXTERNAL INTERRUPT 0 PRIORITY
sbit at	0xB9	PT0;	//IP.1 - TIMER 0 PRIORITY
sbit at	0xBA	PX1;	//IP.2 - EXTERNAL INTERRUPT 1 PRIORITY
sbit at	0xBB	PT1;	//IP.3 - TIMER 1 PRIORITY
sbit at	0xBC	PS;	//IP.4 - SERIAL PORT PRIORITY
sbit at	0xBD	PT2;	//IP.5 - TIMER 2 PRIORITY
sbit at	0xBE	PADC;	//IP.6 - ADC PRIORITY
sbit at	0xBF	PSI;	//IP.7 - SPI OR 2-WIRE SERIAL INTERFACE PRIORITY
sbit at	0xC0	WDWR;	//WDCON.0 - WATCHDOG WRITE ENABLE
sbit at	0xC1	WDE;	//WDCON.1 - WATCHDOG ENABLE
sbit at	0xC2	WDS;	//WDCON.2 - WATCHDOG STATUS BIT
sbit at	0xC3	WDIR;	//WDCON.3 - WATCHDOG INTERRUPT RESPONSE ENABLE BIT
sbit at	0xC4	PRE0;	//WDCON.4 - WATCHDOG TIMEOUT SELECTION BIT0
sbit at	0xC5	PRE1;	//WDCON.5 - WATCHDOG TIMEOUT SELECTION BIT1
sbit at	0xC6	PRE2;	//WDCON.6 - WATCHDOG TIMEOUT SELECTION BIT2
sbit at	0xC7	PRE3;	//WDCON.7 - WATCHDOG TIMEOUT SELECTION BIT3
sbit at	0xC8	CAP2;	//T2CON.0 - CAPTURE OR RELOAD SELECT
sbit at	0xC9	CNT2;	//T2CON.1 - TIMER OR COUNTER SELECT
sbit at	0xCA	TR2;	//T2CON.2 - TIMER 2 ON/OFF CONTROL
sbit at	0xCB	EXEN2;	//T2CON.3 - TIMER 2 EXTERNAL ENABLE FLAG
sbit at	0xCC	TCLK;	//T2CON.4 - TRANSMIT CLOCK SELECT
sbit at	0xCD	RCLK;	//T2CON.5 - RECEIVE CLOCK SELECTT
sbit at	0xCE	EXF2;	//T2CON.6 - EXTERNAL TRANSITION FLAG
sbit at	0xCF	TF2;	//T2CON.7 - TIMER 2 OVERFLOW FLAG
sbit at	0xD0	P;	//PSW.0 - ACCUMULATOR PARITY FLAG
sbit at	0xD1	F1;	//PSW.1 - FLAG 0
sbit at	0xD2	OV;	//PSW.2 - OVERFLOW FLAG
sbit at	0xD3	RS0;	//PSW.3 - REGISTER BANK SELECT 0
sbit at	0xD4	RS1;	//PSW.4 - REGISTER BANK SELECT 1
sbit at	0xD5	F0;	//PSW.5 - FLAG 0
sbit at	0xD6	AC;	//PSW.6 - AUXILIARY CARRY FLAG
sbit at	0xD7	CY;	//PSW.7 - CARRY FLAG
sbit at	0xD8	CS0;	//ADCCON2.0 - ADC INPUT CHANNEL SELECT BIT0
sbit at	0xD9	CS1;	//ADCCON2.1 - ADC INPUT CHANNEL SELECT BIT1
sbit at	0xDA	CS2;	//ADCCON2.2 - ADC INPUT CHANNEL SELECT BIT2
sbit at	0xDB	CS3;	//ADCCON2.3 - ADC INPUT CHANNEL SELECT BIT3
sbit at	0xDC	SCONV;	//ADCCON2.4 - SINGLE CONVERSION ENABLE
sbit at	0xDD	CCONV;	//ADCCON2.5 - CONTINUOUS CONVERSION ENABLE
sbit at	0xDE	DMA;	//ADCCON2.6 - DMA MODE ENABLE
sbit at	0xDF	ADCI;	//ADCCON2.7 - ADC INTURRUPT FLAG
sbit at	0xEB	D0EN;	//DCON.3 - D0 ENABLE BIT
sbit at	0xED	D0;	//DCON.5 - D0 DATA BIT
sbit at	0xEE	D1EN;	//DCON.6 - D1 ENABLE BIT
sbit at	0xEF	D1;	//DCON.7 - D1 DATA BIT
sbit at	0xE8	I2CI;	//I2CCON.0 - I2C INTURRUPT FLAG
sbit at	0xE9	I2CTX;	//I2CCON.1 - I2C TRANSMIT SELECT
sbit at	0xEA	I2CRS;	//I2CCON.2 - I2C RESET
sbit at	0xEB	I2CM;	//I2CCON.3 - I2C MASTER MODE SELECT
sbit at	0xEC	MDI;	//I2CCON.4 - I2C MASTER MODE SDATA INPUT
sbit at	0xED	MCO;	//I2CCON.5 - I2C MASTER MODE SCLOCK OUTPUT
sbit at	0xEE	MDE;	//I2CCON.6 - I2C MASTER MODE SDATA ENABLE
sbit at	0xEF	MDO;	//I2CCON.7 - I2C MASTER MODE SDATA OUTPUT
sbit at	0xF8	SPR0;	//SPICON.0 - SPI BITRATE SELECT BIT0
sbit at	0xF9	SPR1;	//SPICON.1 - SPI BITRATE SELECT BIT1
sbit at	0xFA	CPHA;	//SPICON.2 - SPI CLOCK PHASE SELECT
sbit at	0xFB	CPOL;	//SPICON.3 - SPI CLOCK POLARITY SELECT
sbit at	0xFC	SPIM;	//SPICON.4 - SPI MASTER/SLAVE MODE SELECT
sbit at	0xFD	SPE;	//SPICON.5 - SPI INTERFACE ENABLE
sbit at	0xFE	WCOL;	//SPICON.6 - SPI WRITE COLLISION ERROR FLAG
sbit at	0xFF	ISPI;	//SPICON.7 - SPI END OF TRANSFER FLAG

/* P0 */
sbit at 0x80 P0_0;
sbit at 0x81 P0_1;
sbit at 0x82 P0_2;
sbit at 0x83 P0_3;
sbit at 0x84 P0_4;
sbit at 0x85 P0_5;
sbit at 0x86 P0_6;
sbit at 0x87 P0_7;

/* P1 */
sbit at 0x90 P1_0;
sbit at 0x91 P1_1;
sbit at 0x92 P1_2;
sbit at 0x93 P1_3;
sbit at 0x94 P1_4;
sbit at 0x95 P1_5;
sbit at 0x96 P1_6;
sbit at 0x97 P1_7;

/* P2 */
sbit at 0xA0 P2_0;
sbit at 0xA1 P2_1;
sbit at 0xA2 P2_2;
sbit at 0xA3 P2_3;
sbit at 0xA4 P2_4;
sbit at 0xA5 P2_5;
sbit at 0xA6 P2_6;
sbit at 0xA7 P2_7;

/* P3 */
sbit at 0xB0 P3_0;
sbit at 0xB1 P3_1;
sbit at 0xB2 P3_2;
sbit at 0xB3 P3_3;
sbit at 0xB4 P3_4;
sbit at 0xB5 P3_5;
sbit at 0xB6 P3_6;
sbit at 0xB7 P3_7;
